### ISSUE TITLE
Mob "running in fear" pathing

### ISSUE THREAD

**Issue by Stump876** [locus313/Lo5t-WoW-Server#12]
##### CURRENT BEHAVIOUR:

Mobs in certain instances will ignore pathing and gravity. Dead Mines on the ship, mobs will "run in fear" hovering up to the next tier on the ship (to the next closest mob) In the case below DOT killed him.
![image](https://user-images.githubusercontent.com/68164076/90316347-69588d00-ded6-11ea-990f-5d1e89218902.png)

In Blackrock Depths These mobs ran across the gap to pull mobs from the other wing. Then both sets went to ranged distance and were just attacking as if everything was normal.
![image](https://user-images.githubusercontent.com/68164076/90316321-32827700-ded6-11ea-9294-b5a2836d8d33.png)

I want to say it does the same with the shipbuilders in Lost Rigger Cove, Tanaris, but I cant remember and I don't have a screenshot. My point is it might not be limited to instances.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Needless to say, Mobs should abide by the same pathing and gravity rules as players.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter the instances, and let them run away in fear near mobs that should be out of reach
2. 
3.

**Comment by locus313** [comment]
i have seen this issue as well. Looks like there is an uptream ticket opened for it as well:
https://github.com/azerothcore/azerothcore-wotlk/issues/2688

**Comment by locus313** [comment]
issue has been resolve with commit https://github.com/locus313/azerothcore-wotlk/commit/0baecd3e8f65db05a252cba8056360fd56b7cf8c 
Closing this out.
