### ISSUE TITLE
Anomalus

### ISSUE THREAD

**Issue by Stump876** [locus313/Lo5t-WoW-Server#2]
Nexus boss Anomalus will keep his Rift shield up even after the rift is destroyed. Anomalus will also charge rifts, multiple rifts, that should be well out of his range.

**Comment by locus313** [comment]
I saw the same behavior. i opened this as an issue in the upstream project as well. 
https://github.com/azerothcore/azerothcore-wotlk/issues/3274

**Comment by locus313** [comment]
next update will include fixes for anomalus:
https://github.com/locus313/azerothcore-wotlk/commit/c13779eeb435d976e49710803a7cc4ad7dbf0c6b
https://github.com/locus313/azerothcore-wotlk/commit/654940c85898896369de0225340a7e69952f4972

**Comment by locus313** [comment]
updates have been deployed, let me know how it looks now.
