### ISSUE TITLE
Brewfest

### ISSUE THREAD

**Issue by Stump876** [locus313/Lo5t-WoW-Server#23]
##### CURRENT BEHAVIOUR:

Both factions-
Music doesn't play when in the zone. (The best part!)
Unable to receive Synthebrew Goggles

Alliance/Ironforge- The setup carts are still there blocking some of the vendors
Horde/Orgrimmar- Low level hostile mobs are still wandering the camp. Vendor has multiple "Brew of the Month" options

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Music plays. Can receive Synthebrew goggles when you ask for them. Carts are despawned, and mobs are cleared out, vendor only has one option for brew of the month.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go check out the events in Ironforge and Orgrimmar
2. 
3.

**Comment by locus313** [comment]
@Stump876 Music should be working now.

**Comment by locus313** [comment]
opened ticket upstream for the Synthebrew Goggles:
https://github.com/azerothcore/azerothcore-wotlk/issues/3495

**Comment by locus313** [comment]
opened ticket upstream for the low level hostile mobs wandering in the camp:
https://github.com/azerothcore/azerothcore-wotlk/issues/3496

**Comment by locus313** [comment]
@Stump876 today fixes for the Synthebrew Goggles and low level hostile mobs was deployed.

**Comment by locus313** [comment]
@Stump876 for the setup carts that are blocking some vendors. Can you provide a screenshot? I wasn't able the find the spot your referring to.

**Comment by Stump876** [comment]
Seems to have been fixed. Also, not super important, but the "rabbits" used as trigger objects for the game that are typically invisible to non GM players are visible for the brewfest barking. 
![image](https://user-images.githubusercontent.com/68164076/94328022-0130a880-ff64-11ea-8987-f6753c88a60c.png)

I also think this one should be moved to where the arrow is shown. The instructions are "Bark in front of the Auction house" I'd say that's more next to the bank, than in front of the auction house.
![image](https://user-images.githubusercontent.com/68164076/94328047-64bad600-ff64-11ea-87f8-d9a3936d1ae5.png)

**Comment by locus313** [comment]
@Stump876 thanks, I have fixed the visibility on the barker bunny's. As for the location of that one bunny. In the videos I could find it looked like they were much closer to the bank than the auction house. But not finding a video that is during WOTLK. All the ones I could find look to be from later expansions.

**Comment by Stump876** [comment]
Barking can't be completed now, seems like the bunny has to be visible, or something changed in the coding to make it trigger without being seen. I tried all locations in Org.

**Comment by locus313** [comment]
Thanks for letting me know. ill see if I can find a different solution then.

**Comment by locus313** [comment]
I reverted the change for now so should be able to complete the quest again.

**Comment by locus313** [comment]
Found a different solution, deployed it a little while ago. Could you try the quest again?

**Comment by Stump876** [comment]
Working now, on both horde and alliance.

**Comment by locus313** [comment]
I believe all reported issues in this has been resolved. closing this out.
