### ISSUE TITLE
Quest: Catch the wild wolpertinger

### ISSUE THREAD

**Issue by Stump876** [locus313/Lo5t-WoW-Server#24]
##### CURRENT BEHAVIOUR:

Quest is currently missing for both factions  (Sorry, I can't believe I missed this on the first report)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Quest is given by Goldark Snipehunter (alliance), and Goldark Huntsniper (horde) It's the same guy that gives the pink elekk quest. [The Quest](https://www.wowhead.com/quest=11117/catch-the-wild-wolpertinger) was added in patch 3.3.2 Your can see them around when drunk.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Quest is not available at either quest giver, however you can see them when drunk, or wearing synthbrew goggles
2. 
3.

**Comment by locus313** [comment]
@Stump876 deployed an update that should fix this. Let me know if you can see the quest now.

**Comment by Stump876** [comment]
Yes I can see it now. Not exactly critical, but each wolpertinger caught gives credit for 2.

**Comment by locus313** [comment]
Perfect. I saw that as well. Looking into a solution for that.

**Comment by locus313** [comment]
The issue with the Wolpertinger Net giving you 2 per use has been solved and the fix has been deployed
