### ISSUE TITLE
Quest: Sorlof's Booty 

### ISSUE THREAD

**Issue by Stump876** [locus313/Lo5t-WoW-Server#3]
Sorlof's HP regen is too high/fast. The cannon on the ship is unable to kill him before he regenerates his HP.

**Comment by locus313** [comment]
I just tested this, i actually was able to kill him with the cannon. I just had to click really fast on the cannon. But dont think its currently blizzlike behavior.

i opened this as an issue in the upstream project:
https://github.com/azerothcore/azerothcore-wotlk/issues/3298

**Comment by Stump876** [comment]
I probably should make a separate issue but for the quest right before that, the skeletons in the ship's hold (I think they're called sea dogs) tend to fall through the ship when the ship is moving and are unable to be directly attacked. AOE will kill them, but a lot of times you will have to leave the ship in order to loot them in the water where they die. It's not really a quest issue they do drop the quest items needed, but it's more of a mob issue.

**Comment by locus313** [comment]
this issue has been solved and the fix has been deployed
