### ISSUE TITLE
Quest: Adding injury to insult

### ISSUE THREAD

**Issue by locus313** [locus313/Lo5t-WoW-Server#5]
You insult him and walk him over, before we can attack and ambush him he resets.

**Comment by Stump876** [comment]
Can be worked around if you insult him again halfway, or attacking and kiting. But the insult cooldown should hold until you get back to the ambush area. Without damage to kite him, the proximity reset kicks in.

[video link](https://www.youtube.com/watch?time_continue=5&v=jxrTvQlJ-WU&feature=emb_logo)

**Comment by locus313** [comment]
I saw the same behavior. i opened this as an issue in the upstream project:
https://github.com/azerothcore/azerothcore-wotlk/issues/3303

**Comment by locus313** [comment]
After some feedback on the upstream ticket i did some more testing on this. If you just attack him right before you hit the water. he will follow you over to the ambush area. No need to insult him again. I also confirm the insult cooldown is at 25 seconds. Which looks to be correct:
https://wowgaming.altervista.org/aowow/?spell=43315#used-by-item
