### ISSUE TITLE
Mana tombs trash mobs

### ISSUE THREAD

**Issue by Stump876** [locus313/Lo5t-WoW-Server#7]
##### CURRENT BEHAVIOUR:

Trash mobs that shouldn't have the ability such as Ethereal sorcerers, and Nexus Terrors, are putting up a Power Word: shield. This should be limited to the Ethereal Priests. Mobs are also are not getting the Weakened Soul debuff so they chain cast it.

Edit: Looking at the combat log, I kill the priest but the log says he is still casting shield on the sorcerers. So it might not be the mobs that are bugged but the priests. 

Edit2: So there is an unseen priest casting a bubble on mobs, once it fades on most mobs it doesn't return I took a few screenshots of pulling mobs with no priest, then being bubbled and when the bubble fades the log reads : Ethereal Priest's Power Word Shield fades from ____.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Wiki [here](https://wowwiki.fandom.com/wiki/Mana-Tombs) Scroll down for abilities they should use.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Run Mana Tombs see what mobs that aren't priests that cast power word shield.
2. 
3.

**Comment by locus313** [comment]
I just tested this and see the same behavior. opened a ticket in the upstream project:
https://github.com/azerothcore/azerothcore-wotlk/issues/3371

**Comment by locus313** [comment]
A fix for this has been deployed to the server.
