### ISSUE TITLE
Quest: The Hunt is on

### ISSUE THREAD

**Issue by Stump876** [locus313/Lo5t-WoW-Server#9]
##### CURRENT BEHAVIOUR:

Quest giver gives you the Oculus of the Exorcist which allows you to "detect recent users of cultist necromancy" When using the item certain NPCs should look as if in priest shadow form and have a new chat option. while they do have the chat option, they do not have the shadow form look.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Covered above and [here](https://youtu.be/3QKoaZog6PM)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do the quest
2. 
3.

**Comment by locus313** [comment]
opened issue in upstream project:
https://github.com/azerothcore/azerothcore-wotlk/issues/3443

**Comment by locus313** [comment]
This issue has been solved and fix deployed to the server
